name: 3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cudatoolkit=11.8
  - plyfile
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tqdm
  - pip
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
